### ISSUE TITLE
Make an awesome README

### ISSUE THREAD

**Issue by Widdershin** [cyclejs-community/cyclejs-community#1]
- [x] Contributing section (highlight that all contributors are welcome, give examples of how to do it)
- [x] Auto generated list of open issues that are tagged with 'pr-welcome' to aid people finding stuff to work on
- [x] Section on moving your repos into the community or making new ones in the community

**Comment by Widdershin** [comment]
- [ ] Section on moving your repos into the community or making new ones in the community

**Comment by SteveALee** [comment]
> Section on moving your repos into the community or making new ones in the community

Good.  I was wondering about doing a PR for the speech driver if should be new repo.

**Comment by Widdershin** [comment]
We now have an auto-generated list of issues in the README tagged with 'help'. Let's start using that and see how it goes.

I think the README is good enough to consider this closed for the moment.

**Comment by SteveALee** [comment]
I like the 'automagic', and it's cyclejs too :)
