### ISSUE TITLE
I'd like to join!

### ISSUE THREAD

**Issue by gjlaubenstein** [cyclejs-community/cyclejs-community#11]
This is my first venture into an OSS community. I think the ideas behind cycle.js are extremely fascinating and would love to contribute!

**Comment by Widdershin** [comment]
I've invited you, welcome to the community!

Please read and abide by the [code of conduct](https://github.com/cyclejs-community/cyclejs-community/blob/master/CODE-OF-CONDUCT.md).

Also please swing by #7 and introduce yourself 😸 

Feel free to transfer your existing repos into this community, or create some new ones. Check out some of the repos already in the community as well, see if there's anything you're interested in working on.

If you have any questions, just ask  😄

**Comment by hew** [comment]
Welcome!

**Comment by gjlaubenstein** [comment]
Thanks!
