### ISSUE TITLE
Is this repo a good place for small Cycle dev utilities?

### ISSUE THREAD

**Issue by drewdeal** [cyclejs-community/cyclejs-community#13]
If so, I will submit a PR with a small php util (in utilities dir) that converts HTML to hyperscript.

If not, please suggest a better repo where it can help the most people.

**Comment by TylorS** [comment]
@Widdershin Do you see any reason why we wouldn't want to do that?

I think it'd be a great addition.

**Comment by Widdershin** [comment]
Hi @drewdeal,

I love the idea of having a collection of utilities scripts. I would quite like to keep this repo just related to community organization though.

I've created a [utilities](https://github.com/cyclejs-community/utilities) repo, so if you want to add your script there that would be awesome!

**Comment by Widdershin** [comment]
Also, I have invited you to be a community member. If you have time, please stop by the introductions thread and say hi!

https://github.com/cyclejs-community/cyclejs-community/issues/7

**Comment by drewdeal** [comment]
Cool. Trying to push change now.
`remote: Permission to cyclejs-community/utilities.git denied to drewdeal.`

**Comment by Widdershin** [comment]
You might need to check your email and accept my invite to collaborate on
that repo. If that doesn't work, forking the repo and opening a pull
request should do the trick.

**Comment by drewdeal** [comment]
Ok, done. Let me know if you need an MD for that one.
Drop dead simple...
Just: `php hyperViewConverter.php http://cnn.com`

**Comment by Widdershin** [comment]
Awesome, could you make a little section in the `README` documenting what it does and how to use it? 😄

**Comment by drewdeal** [comment]
Thanks guys!

**Comment by TylorS** [comment]
Awesome thanks @drewdeal  :+1:
