### ISSUE TITLE
I'd like to join!

### ISSUE THREAD

**Issue by stepek** [cyclejs-community/cyclejs-community#15]
Please add me as a member. Thanks!

**Comment by TylorS** [comment]
Hi @stepek you should receive an invite soon and welcome to the community. Feel free to introduce yourself here! #7

**Comment by Widdershin** [comment]
Welcome @stepek! Definitely stop by that issue Tylor linked and introduce yourself.

Also please check out and abide by our [code of conduct](https://github.com/cyclejs-community/cyclejs-community/blob/master/CODE-OF-CONDUCT.md).

As a community member, you can create new repositories, transfer existing repositories in, and get involved in any project you're interested in! We only ask that you welcome and encourage collaboration 😺. Please ask in here or message one of us directly on Gitter if you have any questions.
