### ISSUE TITLE
I'd like to join!

### ISSUE THREAD

**Issue by mr-rampage** [cyclejs-community/cyclejs-community#16]
I started learning cycle.js and will be presenting about it at my company. While learning, I'm creating this [RSS PWA Reader](https://github.com/mr-rampage/cycle-reader) using cycle.js to try and stretch the different use cases we face on our projects. So far, I can say it was pain free experience. Most of the pain was dealing with webpack.

I would like to share my project to get community contribution because I don't think I'll ever have the time to get this project to a polished state alone.

As well, I'd like to learn from the cycle.js gurus the best practices and hopefully get more feedback on how to write better FRP code. Thanks!

**Comment by Widdershin** [comment]
Hey sorry my github notifications buried this! I'll add you now :)

**Comment by olpeh** [comment]
Please close this issue, I don't have access. (maybe I should have @Widdershin ?)

**Comment by mr-rampage** [comment]
Thanks!

**Comment by Widdershin** [comment]
@olpeh I made you an owner of this group, sorry for the delay!
