### ISSUE TITLE
Joining CycleJS to contribue!

### ISSUE THREAD

**Issue by denisse-dev** [cyclejs-community/cyclejs-community#17]
Hello!

I'm Andrea, a software developer who is really interested in functional programming, I'd love to be a member of CycleJS and to contribute to this amazing project!

Thanks in advance! 😄

**Comment by Widdershin** [comment]
Welcome @da-edra! Please stop by our introductions thread and tell us about yourself! #7

Also please check out and abide by our [code of conduct](https://github.com/cyclejs-community/cyclejs-community/blob/master/CODE-OF-CONDUCT.md).

As a community member, you can create new repositories, transfer existing repositories in, and get involved in any project you're interested in! We only ask that you welcome and encourage collaboration 😺. Please ask in here or message one of us directly on Gitter if you have any questions.

**Comment by denisse-dev** [comment]
Thanks a lot!

I'll introduce myself in #7 ! 😄
