### ISSUE TITLE
Decide how to structure the driver collection

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/cyclejs-community#2]
I propose a page would be most flexible as like awesome can link to externally maintained stuff. Which of these is best
- Github page?
- wiki Page?
- readme.md or other md file?

[Updated: removed question about repo as this is already an organisation repo]

**Comment by SteveALee** [comment]
I propose a markdown page (easier to maintain and find)

**Comment by TylorS** [comment]
https://github.com/cyclejs-community/awesome-cyclejs#drivers 

I think we need to touch it up though

**Comment by Widdershin** [comment]
I definitely vote for separate repos, potentially with a markdown list.
