### ISSUE TITLE
I'd love to join!

### ISSUE THREAD

**Issue by ghost** [cyclejs-community/cyclejs-community#9]
I really love Cycle.js and its ideas, and have some ideas that might fare better if I place them in this org 😄.  Would really love if I could join!

**Comment by Widdershin** [comment]
I've invited you, welcome to the community.

Please read and abide by the [code of conduct](https://github.com/cyclejs-community/cyclejs-community/blob/master/CODE-OF-CONDUCT.md).

Also please swing by #7 and introduce yourself 😸 

Feel free to transfer your existing repos into this community, or create some new ones.

If you have any questions, just ask  😄
